<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Design;

class DesignSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#1b1464',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#1b1464',
            'menuTextColor' => '#fff',
            'linkColor' => '#1b1464',
            'textColor' => '#000',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#1b1464',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#1b1464',
            'themeName' => '1',
            'group' => 1,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#0b85b7',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#0b85b7',
            'menuTextColor' => '#fff',
            'linkColor' => '#0b85b7',
            'textColor' => '#000',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#0b85b7',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#0b85b7',
            'themeName' => '2',
            'group' => 1,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#1a3563',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#1a3563',
            'menuTextColor' => '#fff',
            'linkColor' => '#1a3563',
            'textColor' => '#000',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#1a3563',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#1a3563',
            'themeName' => '3',
            'group' => 1,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#599540',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#599540',
            'menuTextColor' => '#fff',
            'linkColor' => '#599540',
            'textColor' => '#000',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#599540',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#599540',
            'themeName' => '4',
            'group' => 1,
        ]);

       Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#ba030c',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#ba030c',
            'menuTextColor' => '#fff',
            'linkColor' => '#ba030c',
            'textColor' => '#000',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#ba030c',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#ba030c',
            'themeName' => '5',
            'group' => 1,
        ]);

       Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#1b8b65',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#1b8b65',
            'menuTextColor' => '#fff',
            'linkColor' => '#1b8b65',
            'textColor' => '#000',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#1b8b65',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#1b8b65',
            'themeName' => '6',
            'group' => 1,
        ]);

       Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#0e3d3c',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#0e3d3c',
            'menuTextColor' => '#fff',
            'linkColor' => '#0e3d3c',
            'textColor' => '#000',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#0e3d3c',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#0e3d3c',
            'themeName' => '7',
            'group' => 1,
        ]);

       Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#282828',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#282828',
            'menuTextColor' => '#fff',
            'linkColor' => '#282828',
            'textColor' => '#000',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#282828',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#282828',
            'themeName' => '8',
            'group' => 1,
        ]);

       Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#3d240e',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#3d240e',
            'menuTextColor' => '#fff',
            'linkColor' => '#3d240e',
            'textColor' => '#000',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#3d240e',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#3d240e',
            'themeName' => '9',
            'group' => 1,
        ]);

       Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#3d0e10',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#3d0e10',
            'menuTextColor' => '#fff',
            'linkColor' => '#3d0e10',
            'textColor' => '#000',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#3d0e10',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#3d0e10',
            'themeName' => '10',
            'group' => 1,
        ]);

       Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#3b3d0e',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#3b3d0e',
            'menuTextColor' => '#fff',
            'linkColor' => '#3b3d0e',
            'textColor' => '#000',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#3b3d0e',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#3b3d0e',
            'themeName' => '11',
            'group' => 1,
        ]);


       Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#1b1464',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#1b1464',
            'menuTextColor' => '#fff',
            'linkColor' => '#1b1464',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#1b1464',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#1b1464',
            'themeName' => '1',
            'group' => 2,
        ]);

       Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#0b85b7',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#0b85b7',
            'menuTextColor' => '#fff',
            'linkColor' => '#0b85b7',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#0b85b7',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#0b85b7',
            'themeName' => '2',
            'group' => 2,
        ]);

       Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#1a3563',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#1a3563',
            'menuTextColor' => '#fff',
            'linkColor' => '#1a3563',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#1a3563',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#1a3563',
            'themeName' => '3',
            'group' => 2,
        ]);

       Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#599540',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#599540',
            'menuTextColor' => '#fff',
            'linkColor' => '#599540',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#599540',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#599540',
            'themeName' => '4',
            'group' => 2,
        ]);

       Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#ba030c',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#ba030c',
            'menuTextColor' => '#fff',
            'linkColor' => '#ba030c',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#ba030c',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#ba030c',
            'themeName' => '5',
            'group' => 2,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#0ead77',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#0ead77',
            'menuTextColor' => '#fff',
            'linkColor' => '#0ead77',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#0ead77',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#0ead77',
            'themeName' => '6',
            'group' => 2,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#f0870a',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#f0870a',
            'menuTextColor' => '#fff',
            'linkColor' => '#f0870a',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#f0870a',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#f0870a',
            'themeName' => '6',
            'group' => 2,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => '#808080',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#808080',
            'menuTextColor' => '#fff',
            'linkColor' => '#808080',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#808080',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#808080',
            'themeName' => '6',
            'group' => 2,
        ]);

        Design::create([
            'backgroundColor' => '#0077a2',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g3_1',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#1a3562',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#1a3562',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#1a3562',
            'themeName' => '1',
            'group' => 3,
        ]);

        Design::create([
            'backgroundColor' => '#013571',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g3_2',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#fd0',
            'menuTextColor' => '#013571',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#fd0',
            'buttonTextColor' => '#013571',
            'buttonBorder' => null,
            'headerColor' => '#fd0',
            'themeName' => '2',
            'group' => 3,
        ]);

        Design::create([
            'backgroundColor' => '#8dc73f',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g3_3',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#3e7228',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#3e7228',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#3e7228',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#3e7228',
            'themeName' => '3',
            'group' => 3,
        ]);

        Design::create([
            'backgroundColor' => '#25064c',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g3_4',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#9768d2',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#9768d2',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#9768d2',
            'themeName' => '4',
            'group' => 3,
        ]);

        Design::create([
            'backgroundColor' => '#25064c',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g3_5',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#f0870a',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#f0870a',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#f0870a',
            'themeName' => '5',
            'group' => 3,
        ]);

        Design::create([
            'backgroundColor' => null,
            'backgroundImage' => 'swoosh_1.png',
            'backgroundStyle' => 'no-repeat',
            'sampleImage' => 'g4_1',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#282828',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#1e1e1e',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#fff',
            'themeName' => '1',
            'group' => 4,
        ]);

        Design::create([
            'backgroundColor' => null,
            'backgroundImage' => 'swoosh_2.png',
            'backgroundStyle' => 'no-repeat',
            'sampleImage' => 'g4_2',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#3c4173',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#272b66',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#fff',
            'themeName' => '2',
            'group' => 4,
        ]);


        Design::create([
            'backgroundColor' => null,
            'backgroundImage' => 'swoosh_3.png',
            'backgroundStyle' => 'no-repeat',
            'sampleImage' => 'g4_3',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#568a71',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#214935',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#fff',
            'themeName' => '3',
            'group' => 4,
        ]);

        Design::create([
            'backgroundColor' => null,
            'backgroundImage' => 'swoosh_4.png',
            'backgroundStyle' => 'no-repeat',
            'sampleImage' => 'g4_4',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#c28b34',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => null,
            'buttonBackgroundColor' => '#8d5d18',
            'buttonTextColor' => '#fff',
            'buttonBorder' => null,
            'headerColor' => '#fff',
            'themeName' => '4',
            'group' => 4,
        ]);

        Design::create([
            'backgroundColor' => null,
            'backgroundImage' => 'fade-1.jpg',
            'backgroundStyle' => 'repeat-x',
            'sampleImage' => 'g5_1',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => null,
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => '#ccc',
            'buttonBackgroundColor' => '#61a2ab',
            'buttonTextColor' => '#fff',
            'buttonBorder' => '1px solid',
            'buttonBorderRadius' => '10px',
            'headerColor' => '#fff',
            'themeName' => '1',
            'group' => 5,
        ]);

        Design::create([
            'backgroundColor' => null,
            'backgroundImage' => 'fade-2.jpg',
            'backgroundStyle' => 'repeat-x',
            'sampleImage' => 'g5_2',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => null,
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => '#ccc',
            'buttonBackgroundColor' => '#c3b89c',
            'buttonTextColor' => '#fff',
            'buttonBorder' => '1px solid',
            'buttonBorderRadius' => '10px',
            'headerColor' => '#fff',
            'themeName' => '1',
            'group' => 5,
        ]);

        Design::create([
            'backgroundColor' => null,
            'backgroundImage' => 'fade-3.jpg',
            'backgroundStyle' => 'repeat-x',
            'sampleImage' => 'g5_3',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => null,
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => '#ccc',
            'buttonBackgroundColor' => '#687130',
            'buttonTextColor' => '#fff',
            'buttonBorder' => '1px solid',
            'buttonBorderRadius' => '10px',
            'headerColor' => '#fff',
            'themeName' => '3',
            'group' => 5,
        ]);

        Design::create([
            'backgroundColor' => null,
            'backgroundImage' => 'fade-4.jpg',
            'backgroundStyle' => 'repeat-x',
            'sampleImage' => 'g5_4',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => null,
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => '#ccc',
            'buttonBackgroundColor' => '#cba38e',
            'buttonTextColor' => '#fff',
            'buttonBorder' => '1px solid',
            'buttonBorderRadius' => '10px',
            'headerColor' => '#fff',
            'themeName' => '4',
            'group' => 5,
        ]);

        Design::create([
            'backgroundColor' => null,
            'backgroundImage' => 'fade-5.jpg',
            'backgroundStyle' => 'repeat-x',
            'sampleImage' => 'g5_5',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => null,
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBorderColor' => '#ccc',
            'buttonBackgroundColor' => '#61a2ab',
            'buttonTextColor' => '#fff',
            'buttonBorder' => '1px solid',
            'buttonBorderRadius' => '10px',
            'headerColor' => '#fff',
            'themeName' => '5',
            'group' => 5,
        ]);


        Design::create([
            'backgroundColor' => '#876f60',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g6_1',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#252525',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#252525',
            'buttonTextColor' => '#fff',
            'headerColor' => '#252525',
            'themeName' => '1',
            'group' => 6,
        ]);

        Design::create([
            'backgroundColor' => '#876f60',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g6_2',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#363636',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#363636',
            'buttonTextColor' => '#fff',
            'headerColor' => '#363636',
            'themeName' => '2',
            'group' => 6,
        ]);

        Design::create([
            'backgroundColor' => '#6a6869',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g6_3',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#f06eaa',
            'menuTextColor' => '#000',
            'linkColor' => '#fff',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#f06eaa',
            'buttonTextColor' => '#fff',
            'headerColor' => '#fff',
            'themeName' => '3',
            'group' => 6,
        ]);

        Design::create([
            'backgroundColor' => '#746457',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g6_4',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#372f2d',
            'menuTextColor' => '#000',
            'linkColor' => '#fff',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#372f2d',
            'buttonTextColor' => '#fff',
            'headerColor' => '#fff',
            'themeName' => '4',
            'group' => 6,
        ]);

        Design::create([
            'backgroundColor' => '#ccb4a0',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g6_5',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#ccb4a0',
            'menuTextColor' => '#000',
            'linkColor' => '#fff',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#ccb4a0',
            'buttonTextColor' => '#fff',
            'headerColor' => '#fff',
            'themeName' => '5',
            'group' => 6,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g7_1',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#086287',
            'menuTextColor' => '#fff',
            'linkColor' => '#0B85B7',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#086287',
            'buttonTextColor' => '#fff',
            'headerColor' => '#0B85B7',
            'themeName' => '1',
            'group' => 7,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g7_2',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#136046',
            'menuTextColor' => '#fff',
            'linkColor' => '#1B8B65',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#136046',
            'buttonTextColor' => '#fff',
            'headerColor' => '#1B8B65',
            'themeName' => '2',
            'group' => 7,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g7_3',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#0f1f3b',
            'menuTextColor' => '#fff',
            'linkColor' => '#1A3563',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#0f1f3b',
            'buttonTextColor' => '#fff',
            'headerColor' => '#1A3563',
            'themeName' => '3',
            'group' => 7,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g7_4',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#041413',
            'menuTextColor' => '#fff',
            'linkColor' => '#0e3d3c',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#041413',
            'buttonTextColor' => '#fff',
            'headerColor' => '#0e3d3c',
            'themeName' => '4',
            'group' => 7,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g7_5',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#000',
            'menuTextColor' => '#fff',
            'linkColor' => '#000',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#000',
            'buttonTextColor' => '#fff',
            'headerColor' => '#000',
            'themeName' => '5',
            'group' => 7,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g7_6',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#447131',
            'menuTextColor' => '#fff',
            'linkColor' => '#599540',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#447131',
            'buttonTextColor' => '#fff',
            'headerColor' => '#599540',
            'themeName' => '6',
            'group' => 7,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g7_7',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#140c04',
            'menuTextColor' => '#fff',
            'linkColor' => '#3d240e',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#140c04',
            'buttonTextColor' => '#fff',
            'headerColor' => '#3d240e',
            'themeName' => '7',
            'group' => 7,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g7_8',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#880209',
            'menuTextColor' => '#fff',
            'linkColor' => '#BA030C',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#880209',
            'buttonTextColor' => '#fff',
            'headerColor' => '#BA030C',
            'themeName' => '8',
            'group' => 7,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g7_9',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#140405',
            'menuTextColor' => '#fff',
            'linkColor' => '#3d0e10',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#140405',
            'buttonTextColor' => '#fff',
            'headerColor' => '#3d0e10',
            'themeName' => '9',
            'group' => 7,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g8_1',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#086287',
            'menuTextColor' => '#fff',
            'linkColor' => '#0B85B7',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#086287',
            'buttonTextColor' => '#fff',
            'headerColor' => '#0B85B7',
            'themeName' => '1',
            'group' => 8,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g8_2',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#395f29',
            'menuTextColor' => '#fff',
            'linkColor' => '#599540',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#395f29',
            'buttonTextColor' => '#fff',
            'headerColor' => '#599540',
            'themeName' => '2',
            'group' => 8,
        ]);


        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g8_3',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#4779cf',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#4779cf',
            'buttonTextColor' => '#fff',
            'headerColor' => '#fff',
            'themeName' => '3',
            'group' => 8,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g8_4',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#21908e',
            'menuTextColor' => '#fff',
            'linkColor' => '#0B85B7',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#21908e',
            'buttonTextColor' => '#fff',
            'headerColor' => '#0B85B7',
            'themeName' => '4',
            'group' => 8,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g8_5',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#261d8f',
            'menuTextColor' => '#fff',
            'linkColor' => '#0B85B7',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#261d8f',
            'buttonTextColor' => '#fff',
            'headerColor' => '#0B85B7',
            'themeName' => '5',
            'group' => 8,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g8_6',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#880209',
            'menuTextColor' => '#fff',
            'linkColor' => '#BA030C',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#880209',
            'buttonTextColor' => '#fff',
            'headerColor' => '#BA030C',
            'themeName' => '6',
            'group' => 8,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g8_7',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#0a7e57',
            'menuTextColor' => '#fff',
            'linkColor' => '#0ead77',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#0a7e57',
            'buttonTextColor' => '#fff',
            'headerColor' => '#0ead77',
            'themeName' => '7',
            'group' => 8,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g8_8',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '##716d69',
            'menuTextColor' => '#fff',
            'linkColor' => '#8B8682',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '##716d69',
            'buttonTextColor' => '#fff',
            'headerColor' => '#8B8682',
            'themeName' => '8',
            'group' => 8,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g8_9',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#9b2893',
            'menuTextColor' => '#fff',
            'linkColor' => '#c333b9',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#9b2893',
            'buttonTextColor' => '#fff',
            'headerColor' => '#c333b9',
            'themeName' => '9',
            'group' => 8,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g8_10',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#ff1f1f',
            'menuTextColor' => '#fff',
            'linkColor' => '#ff5252',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#ff1f1f',
            'buttonTextColor' => '#fff',
            'headerColor' => '#ff5252',
            'themeName' => '10',
            'group' => 8,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g9_1',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#086287',
            'menuTextColor' => '#fff',
            'linkColor' => '#0B85B7',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#086287',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#0B85B7',
            'themeName' => '1',
            'group' => 9,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g9_2',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#136046',
            'menuTextColor' => '#fff',
            'linkColor' => '#1B8B65',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#136046',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#1B8B65',
            'themeName' => '2',
            'group' => 9,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g9_3',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#0f1f3b',
            'menuTextColor' => '#fff',
            'linkColor' => '#1A3563',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#0f1f3b',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#1A3563',
            'themeName' => '3',
            'group' => 9,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g9_4',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#041413',
            'menuTextColor' => '#fff',
            'linkColor' => '#0e3d3c',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#041413',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#0e3d3c',
            'themeName' => '4',
            'group' => 9,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g9_5',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#000',
            'menuTextColor' => '#fff',
            'linkColor' => '#000',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#000',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#000',
            'themeName' => '5',
            'group' => 9,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g9_6',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#447131',
            'menuTextColor' => '#fff',
            'linkColor' => '#599540',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#447131',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#599540',
            'themeName' => '6',
            'group' => 9,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g9_7',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#140c04',
            'menuTextColor' => '#fff',
            'linkColor' => '#3d240e',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#140c04',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#3d240e',
            'themeName' => '7',
            'group' => 9,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g9_8',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#100c3a',
            'menuTextColor' => '#fff',
            'linkColor' => '#1B1464',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#100c3a',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#1B1464',
            'themeName' => '8',
            'group' => 9,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g9_9',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#880209',
            'menuTextColor' => '#fff',
            'linkColor' => '#BA030C',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#880209',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#BA030C',
            'themeName' => '9',
            'group' => 9,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g9_10',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#140405',
            'menuTextColor' => '#fff',
            'linkColor' => '#140405',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#140405',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#140405',
            'themeName' => '10',
            'group' => 9,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g10_1',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#086287',
            'menuTextColor' => '#fff',
            'linkColor' => '#0B85B7',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#086287',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#0B85B7',
            'themeName' => '1',
            'group' => 10,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g10_2',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#395f29',
            'menuTextColor' => '#fff',
            'linkColor' => '#599540',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#395f29',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#599540',
            'themeName' => '2',
            'group' => 10,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g10_3',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#4779cf',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#4779cf',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#fff',
            'themeName' => '3',
            'group' => 10,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g10_4',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#21908e',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#21908e',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#fff',
            'themeName' => '4',
            'group' => 10,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g10_5',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#261d8f',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#261d8f',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#fff',
            'themeName' => '5',
            'group' => 10,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g10_6',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#880209',
            'menuTextColor' => '#fff',
            'linkColor' => '#BA030C',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#880209',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#BA030C',
            'themeName' => '6',
            'group' => 10,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g10_7',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#0a7e57',
            'menuTextColor' => '#fff',
            'linkColor' => '#0ead77',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#0a7e57',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#0ead77',
            'themeName' => '7',
            'group' => 10,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g10_8',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#716d69',
            'menuTextColor' => '#fff',
            'linkColor' => '#8B8682',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#716d69',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#8B8682',
            'themeName' => '8',
            'group' => 10,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g10_9',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#9b2893',
            'menuTextColor' => '#fff',
            'linkColor' => '#c333b9',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#9b2893',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#c333b9',
            'themeName' => '9',
            'group' => 10,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g10_10',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#ff1f1f',
            'menuTextColor' => '#fff',
            'linkColor' => '#ff5252',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#ff1f1f',
            'buttonTextColor' => '#fff',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#ff5252',
            'themeName' => '10',
            'group' => 10,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g11_1',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#086287',
            'menuTextColor' => '#fff',
            'linkColor' => '#0B85B7',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#fff',
            'buttonTextColor' => '#0B85B7',
            'buttonBorder' => '3px solid #086287',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#0B85B7',
            'themeName' => '1',
            'group' => 11,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g11_2',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#136046',
            'menuTextColor' => '#fff',
            'linkColor' => '#1B8B65',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#fff',
            'buttonTextColor' => '#1B8B65',
            'buttonBorder' => '3px solid #136046',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#1B8B65',
            'themeName' => '2',
            'group' => 11,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g11_3',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#0f1f3b',
            'menuTextColor' => '#fff',
            'linkColor' => '#1A3563',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#fff',
            'buttonTextColor' => '#1A3563',
            'buttonBorder' => '3px solid #0f1f3b',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#1A3563',
            'themeName' => '3',
            'group' => 11,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g11_4',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#041413',
            'menuTextColor' => '#fff',
            'linkColor' => '#0e3d3c',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#fff',
            'buttonTextColor' => '#0e3d3c',
            'buttonBorder' => '3px solid #041413',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#0e3d3c',
            'themeName' => '4',
            'group' => 11,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g11_5',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#000',
            'menuTextColor' => '#fff',
            'linkColor' => '#000',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#fff',
            'buttonTextColor' => '#000',
            'buttonBorder' => '3px solid #000',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#000',
            'themeName' => '5',
            'group' => 11,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g11_6',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#447131',
            'menuTextColor' => '#fff',
            'linkColor' => '#599540',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#fff',
            'buttonTextColor' => '#BA030C',
            'buttonBorder' => '3px solid #447131',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#599540',
            'themeName' => '6',
            'group' => 11,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g11_7',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#140c04',
            'menuTextColor' => '#fff',
            'linkColor' => '#3d240e',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#fff',
            'buttonTextColor' => '#3d240e',
            'buttonBorder' => '3px solid #140c04',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#3d240e',
            'themeName' => '7',
            'group' => 11,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g11_8',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#100c3a',
            'menuTextColor' => '#fff',
            'linkColor' => '#1B1464',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#fff',
            'buttonTextColor' => '#1B1464',
            'buttonBorder' => '3px solid #100c3a',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#1B1464',
            'themeName' => '8',
            'group' => 11,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g11_9',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#880209',
            'menuTextColor' => '#fff',
            'linkColor' => '#BA030C',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#fff',
            'buttonTextColor' => '#BA030C',
            'buttonBorder' => '3px solid #880209',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#BA030C',
            'themeName' => '9',
            'group' => 11,
        ]);

        Design::create([
            'backgroundColor' => '#fff',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g11_10',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#140405',
            'menuTextColor' => '#fff',
            'linkColor' => '#3d0e10',
            'textColor' => '#000',
            'buttonBackgroundColor' => '#fff',
            'buttonTextColor' => '#3d0e10',
            'buttonBorder' => '3px solid #140405',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#3d0e10',
            'themeName' => '10',
            'group' => 11,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g12_1',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#9b2893',
            'menuTextColor' => '#fff',
            'linkColor' => '#c333b9',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#000',
            'buttonTextColor' => '#c333b9',
            'buttonBorder' => '3px solid #9b2893',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#c333b9',
            'themeName' => '1',
            'group' => 12,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g12_2',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#395f29',
            'menuTextColor' => '#fff',
            'linkColor' => '#599540',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#000',
            'buttonTextColor' => '#599540',
            'buttonBorder' => '3px solid #395f29',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#599540',
            'themeName' => '2',
            'group' => 12,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g12_3',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#4779cf',
            'menuTextColor' => '#fff',
            'linkColor' => '#2f60b4',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#000',
            'buttonTextColor' => '#2f60b4',
            'buttonBorder' => '3px solid #4779cf',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#2f60b4',
            'themeName' => '3',
            'group' => 12,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g12_4',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#21908e',
            'menuTextColor' => '#fff',
            'linkColor' => '#186665',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#000',
            'buttonTextColor' => '#186665',
            'buttonBorder' => '3px solid #21908e',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#186665',
            'themeName' => '4',
            'group' => 12,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g12_5',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#261d8f',
            'menuTextColor' => '#fff',
            'linkColor' => '#fff',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#000',
            'buttonTextColor' => '#fff',
            'buttonBorder' => '3px solid #261d8f',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#fff',
            'themeName' => '5',
            'group' => 12,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g12_6',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#880209',
            'menuTextColor' => '#fff',
            'linkColor' => '#BA030C',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#000',
            'buttonTextColor' => '#BA030C',
            'buttonBorder' => '3px solid #880209',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#BA030C',
            'themeName' => '6',
            'group' => 12,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g12_7',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#0a7e57',
            'menuTextColor' => '#fff',
            'linkColor' => '#0ead77',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#000',
            'buttonTextColor' => '#0ead77',
            'buttonBorder' => '3px solid #0a7e57',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#0ead77',
            'themeName' => '7',
            'group' => 12,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g12_8',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#716d69',
            'menuTextColor' => '#fff',
            'linkColor' => '#8B8682',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#000',
            'buttonTextColor' => '#8B8682',
            'buttonBorder' => '3px solid #716d69',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#8B8682',
            'themeName' => '8',
            'group' => 12,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g12_9',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#9b2893',
            'menuTextColor' => '#fff',
            'linkColor' => '#c333b9',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#000',
            'buttonTextColor' => '#c333b9',
            'buttonBorder' => '3px solid #9b2893',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#c333b9',
            'themeName' => '9',
            'group' => 12,
        ]);

        Design::create([
            'backgroundColor' => '#000',
            'backgroundImage' => null,
            'backgroundStyle' => null,
            'sampleImage' => 'g12_10',
            'backgroundGradientStartColor' => null,
            'backgroundGradientEndColor' => null,
            'backgroundGradientStyle' => null,
            'menuBackgroundColor' => '#ff1f1f',
            'menuTextColor' => '#fff',
            'linkColor' => '#ff5252',
            'textColor' => '#fff',
            'buttonBackgroundColor' => '#000',
            'buttonTextColor' => '#ff5252',
            'buttonBorder' => '3px solid #ff1f1f',
            'buttonBorderRadius' => '30px',
            'headerColor' => '#ff5252',
            'themeName' => '10',
            'group' => 12,
        ]);

    }
}
